package com.demo.test;

import java.time.LocalDate;

public class TestPoly {
	public static void main(String[] args) {
		
		BaseForPoly b=new ExtendBase(LocalDate.of(2023, 9, 21),12,"Shubham");
		System.out.println(b.generateId());
		
		BaseForPoly b2=new BaseForPoly(12,"Shubham");
		System.out.println("Id generated by base class :-"+b2.generateId());
	}
}
